version: "3"

services:
  loki:
    image: grafana/loki:2.0.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  web:
    build:
      context: ./src/web
    ports:
      - 5000:80
    networks:
      - loki

  grafana:
    image: grafana/grafana:7.3.5
    ports:
      - 3000:3000
    volumes:
    - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    networks:
      - loki

networks:
  loki: